"""
LangFuse v4 tracing wrapper with session tracking.

Falls back to console logging when LangFuse is not configured.
Session stats are maintained in-process (no LangFuse query API needed).
"""

import logging
import os
from typing import Any, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Module-level state
# ---------------------------------------------------------------------------

_client: Any = None
_client_initialized = False

_current_session_id: Optional[str] = None

_stats: dict = {
    "total_calls": 0,
    "total_latency_ms": 0.0,
    "error_count": 0,
}


# ---------------------------------------------------------------------------
# Client initialisation
# ---------------------------------------------------------------------------


def _build_client() -> Optional[Any]:
    """Attempt to build a LangFuse client from environment variables."""
    public_key = os.getenv("LANGFUSE_PUBLIC_KEY")
    secret_key = os.getenv("LANGFUSE_SECRET_KEY")
    host = os.getenv("LANGFUSE_HOST", "https://cloud.langfuse.com")

    if not public_key or not secret_key:
        logger.info("LangFuse env vars not set — traces will be logged to console only.")
        return None

    try:
        from langfuse import Langfuse  # type: ignore

        client = Langfuse(public_key=public_key, secret_key=secret_key, host=host)
        logger.info("LangFuse client initialised (v4).")
        return client
    except Exception as exc:
        logger.warning("Failed to initialise LangFuse client: %s", exc)
        return None


def _get_client() -> Optional[Any]:
    """Return a cached LangFuse client, creating it on first call."""
    global _client, _client_initialized
    if not _client_initialized:
        _client = _build_client()
        _client_initialized = True
    return _client


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def configure_session(session_id: str) -> None:
    """
    Set the active session ID and reset per-session statistics.

    Call this once per Streamlit session (or eval run) before any trace_call()
    invocations.  The session_id is attached to every subsequent LangFuse
    observation so traces can be grouped in the dashboard.

    Args:
        session_id: A UUID string generated by the caller.
    """
    global _current_session_id, _stats
    _current_session_id = session_id
    _stats = {"total_calls": 0, "total_latency_ms": 0.0, "error_count": 0}
    logger.debug("LangFuse session configured: %s", session_id)


def trace_call(
    model_name: str,
    prompt: str,
    response: str,
    latency_ms: float,
    metadata: Optional[dict] = None,
    session_id: Optional[str] = None,
) -> None:
    """
    Record one LLM API call in LangFuse (or the console when unavailable).

    Updates in-process session statistics regardless of whether LangFuse
    is configured.

    Args:
        model_name: Identifier of the model that produced the response.
        prompt:     The user-facing prompt sent to the model.
        response:   The text the model returned.
        latency_ms: Wall-clock latency for the API round-trip in milliseconds.
        metadata:   Optional dict of extra fields to attach to the trace.
        session_id: Optional session identifier; falls back to the module-level
                    session set via configure_session().
    """
    metadata = metadata or {}
    sid = session_id or _current_session_id

    # Track in-process stats
    _stats["total_calls"] += 1
    _stats["total_latency_ms"] += latency_ms
    if "error" in response.lower() and len(response) < 120:
        _stats["error_count"] += 1

    client = _get_client()

    if client is None:
        logger.info(
            "[TRACE] session=%s model=%s latency=%.1fms prompt_chars=%d response_chars=%d",
            sid,
            model_name,
            latency_ms,
            len(prompt),
            len(response),
        )
        return

    try:
        obs = client.start_observation(
            name="llm_call",
            as_type="generation",
            model=model_name,
            input=prompt,
            output=response,
            metadata={
                "latency_ms": latency_ms,
                "session_id": sid,
                **metadata,
            },
        )
        obs.end()
        client.flush()
    except Exception as exc:
        logger.warning("LangFuse trace_call failed (non-fatal): %s", exc)


def get_session_stats() -> dict:
    """
    Return aggregated statistics for the current session.

    Stats are maintained in-process from every trace_call() invocation.
    LangFuse is not queried directly (no remote round-trip).

    Returns:
        Dict with keys: total_calls, avg_latency_ms, error_count.
    """
    calls = _stats["total_calls"]
    avg = _stats["total_latency_ms"] / calls if calls > 0 else 0.0
    return {
        "total_calls": calls,
        "avg_latency_ms": round(avg, 1),
        "error_count": _stats["error_count"],
    }
