"""
LangFuse v4 tracing wrapper with session tracking.

Falls back to console logging when LangFuse is not configured.
Session stats are stored in Redis, keyed by session_id, so they survive
process restarts and stay correct across multiple Streamlit workers. Falls
back to in-process state when REDIS_URL is not configured.
"""

import logging
import os
from typing import Any, Optional

from observability.redis_client import get_client as get_redis_client

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Module-level state
# ---------------------------------------------------------------------------

_client: Any = None
_client_initialized = False

_current_session_id: Optional[str] = None

_stats: dict = {
    "total_calls": 0,
    "total_latency_ms": 0.0,
    "error_count": 0,
}

_STATS_KEY_PREFIX = "llm_benchmark:session_stats:"


def _stats_key(session_id: str) -> str:
    return f"{_STATS_KEY_PREFIX}{session_id}"


# ---------------------------------------------------------------------------
# Client initialisation
# ---------------------------------------------------------------------------


def _build_client() -> Optional[Any]:
    """Attempt to build a LangFuse client from environment variables."""
    public_key = os.getenv("LANGFUSE_PUBLIC_KEY")
    secret_key = os.getenv("LANGFUSE_SECRET_KEY")
    host = os.getenv("LANGFUSE_HOST", "https://cloud.langfuse.com")

    if not public_key or not secret_key:
        logger.info("LangFuse env vars not set — traces will be logged to console only.")
        return None

    try:
        from langfuse import Langfuse  # type: ignore

        client = Langfuse(public_key=public_key, secret_key=secret_key, host=host)
        logger.info("LangFuse client initialised (v4).")
        return client
    except Exception as exc:
        logger.warning("Failed to initialise LangFuse client: %s", exc)
        return None


def _get_client() -> Optional[Any]:
    """Return a cached LangFuse client, creating it on first call."""
    global _client, _client_initialized
    if not _client_initialized:
        _client = _build_client()
        _client_initialized = True
    return _client


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def configure_session(session_id: str) -> None:
    """
    Set the active session ID and reset per-session statistics.

    Call this once per Streamlit session (or eval run) before any trace_call()
    invocations.  The session_id is attached to every subsequent LangFuse
    observation so traces can be grouped in the dashboard.

    Args:
        session_id: A UUID string generated by the caller.
    """
    global _current_session_id, _stats
    _current_session_id = session_id
    _stats = {"total_calls": 0, "total_latency_ms": 0.0, "error_count": 0}

    redis_client = get_redis_client()
    if redis_client is not None:
        try:
            redis_client.delete(_stats_key(session_id))
            redis_client.hset(
                _stats_key(session_id),
                mapping={"total_calls": 0, "total_latency_ms": 0.0, "error_count": 0},
            )
        except Exception as exc:
            logger.warning("Redis session reset failed (non-fatal): %s", exc)

    logger.debug("LangFuse session configured: %s", session_id)


def trace_call(
    model_name: str,
    prompt: str,
    response: str,
    latency_ms: float,
    metadata: Optional[dict] = None,
    session_id: Optional[str] = None,
) -> None:
    """
    Record one LLM API call in LangFuse (or the console when unavailable).

    Updates in-process session statistics regardless of whether LangFuse
    is configured.

    Args:
        model_name: Identifier of the model that produced the response.
        prompt:     The user-facing prompt sent to the model.
        response:   The text the model returned.
        latency_ms: Wall-clock latency for the API round-trip in milliseconds.
        metadata:   Optional dict of extra fields to attach to the trace.
        session_id: Optional session identifier; falls back to the module-level
                    session set via configure_session().
    """
    metadata = metadata or {}
    sid = session_id or _current_session_id
    is_error = "error" in response.lower() and len(response) < 120

    # Track in-process stats (used as a fallback when Redis is unavailable)
    _stats["total_calls"] += 1
    _stats["total_latency_ms"] += latency_ms
    if is_error:
        _stats["error_count"] += 1

    redis_client = get_redis_client()
    if redis_client is not None and sid is not None:
        try:
            key = _stats_key(sid)
            redis_client.hincrby(key, "total_calls", 1)
            redis_client.hincrbyfloat(key, "total_latency_ms", latency_ms)
            if is_error:
                redis_client.hincrby(key, "error_count", 1)
        except Exception as exc:
            logger.warning("Redis stats update failed (non-fatal): %s", exc)

    client = _get_client()

    if client is None:
        logger.info(
            "[TRACE] session=%s model=%s latency=%.1fms prompt_chars=%d response_chars=%d",
            sid,
            model_name,
            latency_ms,
            len(prompt),
            len(response),
        )
        return

    try:
        obs = client.start_observation(
            name="llm_call",
            as_type="generation",
            model=model_name,
            input=prompt,
            output=response,
            metadata={
                "latency_ms": latency_ms,
                "session_id": sid,
                **metadata,
            },
        )
        obs.end()
        client.flush()
    except Exception as exc:
        logger.warning("LangFuse trace_call failed (non-fatal): %s", exc)


def get_session_stats() -> dict:
    """
    Return aggregated statistics for the current session.

    Reads from Redis when configured (so stats survive restarts and are
    shared across Streamlit workers); falls back to in-process state
    maintained by every trace_call() invocation otherwise. LangFuse is
    never queried directly (no remote round-trip).

    Returns:
        Dict with keys: total_calls, avg_latency_ms, error_count.
    """
    redis_client = get_redis_client()
    if redis_client is not None and _current_session_id is not None:
        try:
            raw = redis_client.hgetall(_stats_key(_current_session_id))
            if raw:
                calls = int(float(raw.get("total_calls", 0)))
                total_latency = float(raw.get("total_latency_ms", 0.0))
                avg = total_latency / calls if calls > 0 else 0.0
                return {
                    "total_calls": calls,
                    "avg_latency_ms": round(avg, 1),
                    "error_count": int(float(raw.get("error_count", 0))),
                }
        except Exception as exc:
            logger.warning("Redis stats read failed, using in-process state: %s", exc)

    calls = _stats["total_calls"]
    avg = _stats["total_latency_ms"] / calls if calls > 0 else 0.0
    return {
        "total_calls": calls,
        "avg_latency_ms": round(avg, 1),
        "error_count": _stats["error_count"],
    }
